In [1]:
import numpy as np
import pandas as pd

In [2]:
dt=pd.read_excel("StudentPrediction.xlsx")

In [3]:
dt

    Hours_Studied  Sleep_Hours  Attendance  Previous_Score  Final_Score
0               2            6          65              50           52
1               3            7          70              55           58
2               4            6          75              60           62
3               5            7          80              65           68
4               6            8          85              70           75
5               7            7          90              75           80
6               8            6          92              78           83
7               1            5          60              45           48
8               2            6          68              52           55
9               3            7          72              58           60
10              4            8          78              62           65
11              5            6          82              67           70
12              6            7          88              72           78
13              7            8          91              76           82
14              8            7          94              80           86
15              2            6          66              51           54
16              3            7          71              57           59
17              4            6          76              61           63
18              5            7          81              66           69
19              6            8          86              71           76
20              7            7          89              74           79
21              8            6          93              79           84

In [4]:
dt.shape

(22, 5)

In [5]:
dt.describe()

       Hours_Studied  Sleep_Hours  Attendance  Previous_Score  Final_Score
count      22.000000    22.000000   22.000000       22.000000    22.000000
mean        4.818182     6.727273   79.636364       64.727273    68.454545
std         2.174229     0.827032   10.219242       10.370204    11.578828
min         1.000000     5.000000   60.000000       45.000000    48.000000
25%         3.000000     6.000000   71.250000       57.250000    59.250000
50%         5.000000     7.000000   80.500000       65.500000    68.500000
75%         6.750000     7.000000   88.750000       73.500000    78.750000
max         8.000000     8.000000   94.000000       80.000000    86.000000

In [6]:
dt.tail()

    Hours_Studied  Sleep_Hours  Attendance  Previous_Score  Final_Score
17              4            6          76              61           63
18              5            7          81              66           69
19              6            8          86              71           76
20              7            7          89              74           79
21              8            6          93              79           84

In [7]:
dt.head()

   Hours_Studied  Sleep_Hours  Attendance  Previous_Score  Final_Score
0              2            6          65              50           52
1              3            7          70              55           58
2              4            6          75              60           62
3              5            7          80              65           68
4              6            8          85              70           75

In [8]:
dt.isna().count()

Hours_Studied     22
Sleep_Hours       22
Attendance        22
Previous_Score    22
Final_Score       22
dtype: int64

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
lin=LinearRegression()

In [11]:
x=dt[["Hours_Studied","Sleep_Hours"]]
y=dt["Final_Score"]

In [12]:
lin.fit(x,y)

LinearRegression()

In [13]:
lin.predict([[5,10]])

C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([72.33564955])

In [14]:
lin.coef_

array([5.15151057, 0.89969789])

In [15]:
lin.intercept_

np.float64(37.581117824773415)

In [16]:
from sklearn.preprocessing import PolynomialFeatures

In [17]:
poly=PolynomialFeatures()

In [18]:
x_poly=poly.fit_transform(x)

In [19]:
lin_poly=LinearRegression()

In [20]:
lin_poly.fit(x_poly,y)

LinearRegression()

In [21]:
lin_poly.predict(poly.fit_transform([[5,10]]))

array([70.03013558])

In [22]:
dt

    Hours_Studied  Sleep_Hours  Attendance  Previous_Score  Final_Score
0               2            6          65              50           52
1               3            7          70              55           58
2               4            6          75              60           62
3               5            7          80              65           68
4               6            8          85              70           75
5               7            7          90              75           80
6               8            6          92              78           83
7               1            5          60              45           48
8               2            6          68              52           55
9               3            7          72              58           60
10              4            8          78              62           65
11              5            6          82              67           70
12              6            7          88              72           78
13              7            8          91              76           82
14              8            7          94              80           86
15              2            6          66              51           54
16              3            7          71              57           59
17              4            6          76              61           63
18              5            7          81              66           69
19              6            8          86              71           76
20              7            7          89              74           79
21              8            6          93              79           84